#!/usr/bin/env bash
# scripts/run-matrix.sh reads VM_HOST, SSH_KEY and HOST_IMAGE_DIR from the
# .test-env the matrix harness writes -- in the harness's own format.
#
# The harness's run-tests.sh (write_env_file) writes every line as
# `export NAME="value"`, and sources the file to read it back. run-matrix.sh
# used to grep for `^VM_HOST=` and keep everything after the `=`, so it never
# matched a file the harness wrote, and its SSH connection mux never started
# (#411). A file written by hand, or rewritten by scripts/vm.sh, has bare
# `NAME=value` lines; that format must keep working too.
#
# Black-box: the real run-matrix.sh runs in a sandbox, beside a stand-in
# harness, with a stand-in `ssh` on PATH that records what it was asked to do
# and then fails, so the mux reports "did not start" and the run carries on.
# What the stand-in was asked to connect to, and with which key, is the
# evidence that the values were read.
#
# Quiet on success (the scripts tier is budgeted): one summary line.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/run-matrix-test-env.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

pass=0
fail=0
ok() { pass=$((pass + 1)); }
bad() {
    fail=$((fail + 1))
    printf '  FAIL  %s\n' "$1"
    [ -n "${2:-}" ] && printf '%s\n' "$2" | sed 's/^/        /'
    return 0
}

mkdir -p "$tmp/consumer/scripts" "$tmp/fs-windows-test-harness/scripts" "$tmp/bin" "$tmp/msys-bin"
cp "$ROOT/scripts/run-matrix.sh" "$tmp/consumer/scripts/run-matrix.sh"
: > "$tmp/key"

# The harness: record that it ran, and succeed.
# shellcheck disable=SC2016 # expands in the generated script
printf '#!/usr/bin/env bash\necho ran >> "$HARNESS_LOG"\n' \
    > "$tmp/fs-windows-test-harness/scripts/run-tests.sh"

# ssh: record the argument list, one call per line, then fail as an
# unreachable host does. The mux master then never makes its socket.
# shellcheck disable=SC2016 # expands in the generated script
printf '#!/usr/bin/env bash\nprintf "%%s\\n" "$*" >> "$SSH_LOG"\nexit 255\n' > "$tmp/bin/ssh"
chmod +x "$tmp/bin/ssh"

# uname as Git Bash on a Windows runner answers it.
printf '#!/usr/bin/env bash\necho MINGW64_NT-10.0-20348\n' > "$tmp/msys-bin/uname"
chmod +x "$tmp/msys-bin/uname"

# run_matrix CASE [EXTRA_PATH] -- run the sandboxed run-matrix.sh with a
# scenario filter unique to this test and case, so its lock cannot collide.
run_matrix() {
    local case="$1" extra="${2:-}"
    rm -rf "$tmp/consumer/diskimages" "$tmp/host images"
    : > "$tmp/ssh.log"
    : > "$tmp/harness.log"
    # VM_HOST in the environment must lose to the file, as it does for the
    # harness, which sources the file over whatever it inherited.
    VM_HOST=from-the-environment@elsewhere \
    SSH_LOG="$tmp/ssh.log" HARNESS_LOG="$tmp/harness.log" \
    PATH="${extra:+$extra:}$tmp/bin:$PATH" \
        bash "$tmp/consumer/scripts/run-matrix.sh" "run-matrix-test-env-$$-$case" \
        > "$tmp/out.log" 2>&1
    rc=$?
}

# master_call -- the line of ssh.log that started the mux master, if any.
master_call() { grep -e '-o ControlMaster=yes' "$tmp/ssh.log" | head -1; }

# ── 1. The harness's own format ─────────────────────────────────────────────
# Exactly what write_env_file writes, header and all. HOST_IMAGE_DIR is not
# one of the harness's variables; a person adds it, in the same style.
cat > "$tmp/consumer/.test-env" <<EOF
# Generated by fs-windows-test-harness/scripts/run-tests.sh on 2026-10-02 12:00:00.
# Sourced automatically by run-tests.sh on subsequent runs.
# Re-run with --reset to regenerate.
export VM_HOST="runneradmin@localhost"
export VM_WORKDIR="C:/rust-fs-ntfs-matrix"
export VM_IMAGE_DIR="C:/rust-fs-ntfs-matrix"
export SSH_OPTS="-i $tmp/key -o IdentitiesOnly=yes"
export SSH_KEY="$tmp/key"
export HOST_IMAGE_DIR="$tmp/host images"
EOF
run_matrix harness
log="$(cat "$tmp/out.log")"

if [ "$rc" -eq 0 ] && [ -s "$tmp/harness.log" ]; then
    ok
else
    bad "harness format: the run reaches the harness and exits 0 (rc=$rc)" "$log"
fi

m="$(master_call)"
case "$m" in
    *" runneradmin@localhost") ok ;;
    *) bad "harness format: the mux master is started for VM_HOST=runneradmin@localhost" \
        "ssh calls: $(cat "$tmp/ssh.log")" ;;
esac
case "$m" in
    *"-i $tmp/key "*) ok ;;
    *) bad "harness format: the mux master is given SSH_KEY with -i" "master call: ${m:-(none)}" ;;
esac

if [ -d "$tmp/host images" ] && [ ! -e "$tmp/consumer/diskimages" ]; then
    ok
else
    bad "harness format: HOST_IMAGE_DIR (quoted, with a space) is the image directory" \
        "$(ls -A "$tmp/consumer")"
fi

# The VM workdir is the harness's to create: its VM-lock Acquire does
# New-Item on it before anything else touches the VM. run-matrix.sh makes no
# remote call of its own beyond the mux master.
if grep -qi powershell "$tmp/ssh.log"; then
    bad "harness format: run-matrix.sh runs no remote command of its own" "$(cat "$tmp/ssh.log")"
else
    ok
fi

# ── 2. A hand-written file: bare and single-quoted values ───────────────────
# scripts/vm.sh rewrites VM_HOST as a bare NAME=value line.
cat > "$tmp/consumer/.test-env" <<EOF
VM_HOST=chris@172.16.18.253
SSH_KEY='$tmp/key'
VM_WORKDIR=C:/Users/chris/dev/rust-fs-ntfs
EOF
run_matrix bare
m="$(master_call)"
case "$m" in
    *"-i $tmp/key "*" chris@172.16.18.253") ok ;;
    *) bad "hand-written: the mux master is started for chris@172.16.18.253 with SSH_KEY" \
        "ssh calls: $(cat "$tmp/ssh.log")" ;;
esac
if [ -d "$tmp/consumer/diskimages" ]; then
    ok
else
    bad "hand-written: no HOST_IMAGE_DIR falls back to diskimages/" "$(ls -A "$tmp/consumer")"
fi
if grep -qi powershell "$tmp/ssh.log"; then
    bad "hand-written: run-matrix.sh runs no remote command of its own" "$(cat "$tmp/ssh.log")"
else
    ok
fi

# ── 3. Git Bash on a Windows runner ─────────────────────────────────────────
# Its ssh is a Cygwin build: a mux client cannot hand its stdio descriptors
# to the master (`mux_client_request_session: send fds failed`), so every
# multiplexed call would fail. The mux stays off there, and says so.
cat > "$tmp/consumer/.test-env" <<EOF
export VM_HOST="runneradmin@localhost"
export VM_WORKDIR="C:/rust-fs-ntfs-matrix"
export SSH_KEY="$tmp/key"
EOF
run_matrix msys "$tmp/msys-bin"
log="$(cat "$tmp/out.log")"
if [ "$rc" -eq 0 ] && [ -s "$tmp/harness.log" ]; then
    ok
else
    bad "Git Bash: the run reaches the harness and exits 0 (rc=$rc)" "$log"
fi
if [ ! -s "$tmp/ssh.log" ]; then
    ok
else
    bad "Git Bash: no mux master is started" "ssh calls: $(cat "$tmp/ssh.log")"
fi
case "$log" in
    *"SSH mux: off"*) ok ;;
    *) bad "Git Bash: the run says the mux is off, and why" "$log" ;;
esac

printf 'run-matrix-test-env: %d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
